module.exports = {
  CORE: 'core',
  TRANSPORT: 'transport',
  OPTIONS: 'options',
  MFOS_base_url: 'http://localhost:3333/api/v1/',
  MODE_SDK: 'SDK',
  MODE_TRANSPORT: 'Transport',
  ACTION_CORE: 'CORE',
  COMMUNICATION_MODE: 'communicationMode',
  ACTION: 'action',
  TASK: { RUNTEST: 'runTest' },
  EXCLUDED_METHODS: [],
  EXCLUDED_MODULES: [],
  ASYNCHRONOUS: 'asynchronous',
  TOPIC_PUBLISH_SUFFIX: '_FCS',
  TOPIC_SUBSCRIBE_SUFFIX: '_FCA',
  APP_TRANSPORT_UNAVAILABLE: 'App Transport unavailable',
  DEFAULT_DIRECTORY: '/tmp/jsonReports/',
  JSON_FILE_EXTENSION: '_CoreSuiteReport.json',
  DEVICE_MAC: 'deviceMac',
  THIRD_PARTY_APP_ID: 'default3rdPartyAppId',
  LONGPOLL_TIMEOUT: 15000,
  GENERATE_HTML_REPORT: true,
  PUBSUB_COMMUNINCATION_ERROR: 'pubSub communication error',
  INVALID_RESPONSE: 'Invalid response',
  QUEUE_RESPONSE: 'Recieved queue response',
  WRITE_FAILED: 'Unable to write report json to file',
  WRITE_TO_FILE: 'writeToFile',
  EXECUTE_SHELL: 'executeShell',
  DEVICE_MAC_UNAVAILABLE: 'Device MAC unavailable',
  MESSAGE_QUEUE_SIZE: 100,
  MESSAGE_QUEUE_TIME_DIFF: 150000,
  SUBSCRIBE: 'subscribe',
  PUBLISH: 'publish',
  RESPONSE_NOT_FOUND: 'No_Response',
  NO_MATCHED_RESPONSE: 'Unable to find the response for the current request',
  PARAMS: 'Params',
  BOOLEAN: 'boolean',
  NUMBER: 'number',
  STRING: 'string',
  TEST_HANDLER_DATA_UNDEFINED: 'Expected parsed data from fixtures to be defined',
  CYPRESS_MODULES_PATH: 'cypress/fixtures/external/modules',
  EXTERNAL_PATH: 'cypress/fixtures/external/modules/',
  MODULES_PATH: 'cypress/fixtures/modules/',
  DEFAULT_PATH: 'cypress/fixtures/defaultTestData.json',
  SANITY_REPORT_FILE_PATH: getSanityReportPath(),
  LINCHPIN_TIMEOUT: 7000,
  CONTEXT: 'Context',
  CONTEXT_FILE_PATH: 'cypress/fixtures/apiObjectContext.json',
  SANITY_REPORT_LONGPOLL_TIMEOUT: 200000,
  CONTENT: 'Content',
  DEVICE_CONTENT_VALIDATION: 'deviceContentValidation',
  STATIC_CONTENT_VALIDATION: 'staticContentValidation',
  OBJECT: 'object',
  DEFAULT_DEVICE_DATA_PATH: 'cypress/fixtures/defaultDeviceData.json',
  EXTERNAL_DEVICES_PATH: 'cypress/fixtures/external/devices/',
  INPUT: 'INPUT',
  CONFIG: 'CONFIG',
  APPID: 'appId',
  CERTIFICATION: 'certification',
  JOBID: 'jobId',
  SANITY_REPORT_POLLING_TIMEOUT: 'sanityReportPollingTimeout',
  MESSAGE_QUEUE: 'messageQueue',
  READ_FILES_FROM_DIRECTORY: 'readFilesFromDir',
  SEARCH: 'search',
  SOURCE: 'source',
  DEVICE: 'device',
  METADATA: 'metadata',
  IS_NOT_SUPPORTED_API: 'isNotSupportedApi',
  EVENT: 'event',
  EVENT_NAME: 'eventName',
  API_NAME: 'apiName',
  NO_APP_OR_EVENT_OBJECT: 'App or Event Object Not Found',
  ERROR_LIST: ['Method not found', 'Method Not Implemented'],
  STATUS_CODE: [0, 1, 2, 3],
  SCHEMA_VALIDATION_STATUS_CODE: ['PASS', 'FAIL', 'SKIPPED', 'PENDING'],
  GLOBAL_API_OBJECT_LIST: 'apiObjectList',
  GLOBAL_EVENT_OBJECT_LIST: 'eventObjectList',
  NO_DATA: 'no data'
};
function getSanityReportPath() {
  // Check if Cypress is defined, for cypress test context
  if (typeof Cypress !== 'undefined') {
    return `./reports/${Cypress.env('jobId')}/fca_sanity_suite.json`
  }
  // If not in Cypress context, for jest unit test context
  return null;
}
