module.exports = {
  LOGGER_LEVEL: 'debug',
  SUPPORTED_SDK: ['Firebolt'],
  MOCHAWESOME: 'mochawesome',
  CUCUMBER: 'cucumber',
  SANITY_REPORT_FILENAME: 'fca_sanity_suite',
  FIREBOLTCALLS_FROM_FCS: './cypress/fixtures/fireboltCalls/',
  FIREBOLTCALLS_FROM_CONFIGMODULE: './cypress/fixtures/external/fireboltCalls/',
  THIRD_PARTY_APP_ID: 'default3rdPartyAppId',
  SUBSCRIBE: 'subscribe',
  CONTEXT: 'Context',
  PARAMS: 'Params',
  ACTION_CORE: 'CORE',
  NO_PARAMS: 'noParam',
  NO_CONTEXT: 'noContext',
  GLOBAL_API_OBJECT_LIST: 'apiObjectList',
  GLOBAL_EVENT_OBJECT_LIST: 'eventObjectList',
  THIRD_PARTY_APP: '3rd party app',
  TASK: {
    CALLMETHOD: 'callMethod',
    REGISTEREVENT: 'registerEvent',
    GETEVENTRESPONSE: 'getEventResponse',
  },
  IS_SCENARIO_EXEMPTED: 'isScenarioExempted',
  NOT_SUPPORTED_METHODS: 'NOT_SUPPORTED_METHODS',
  TYPE_STRING: 'string',
  TYPE_OBJECT: 'object',
  RESULT: 'result',
  METHOD_CONTENT: 'Method Content validation',
  NO_API_OBJECT: 'Api Object Not Found',
  EXTRACTEDAPI_PATH: 'extractedApiObject.response.',
  NO_CONTENT: 'Expected Content Not found',
  NUMBER: 'number',
  DATE: 'date',
  PASSWORD: 'password',
  EMAIL: 'email',
  DECIMAL: 'decimal',
  HEXADECIMAL: 'hexaDecimal',
  ID: 'id',
  UNIQUEID: 'uniqueid',
  STRING_LANGUAGE_FORMAT: 'stringLanguageFormat',
  STRING_LOCALE_FORMAT: 'stringLocaleFormat',
  ARRAY: 'array',
  STRING: 'string',
  ALPHANUMERIC: 'alphanumeric',
  DEVICEMODULEFORMAT: 'deviceModelFormat',
  OBJECT: 'object',
  COUNTRYCODE: 'countryCode',
  VERSION: 'version',
  TIMEZONE: 'timeZone',
  DECODEVALUE_JSON_PATH: 'decodeValue.json',
  BASE64: 'base64',
  JWT: 'jwt',
  ERROR_NOT_UNDEFINED_CHECK: 'Error not undefined Check',
  ERROR_NULL_CHECK: 'Error null Check',
  SCHEMA_VALIDATION_CHECK: 'Schema validation Check',
  ERROR_INSIDE_RESULT_CHECK: 'Error inside Result check',
  ERROR_EXPECTED_DEFINED: 'Expected response.error to be defined',
  NULL_CHECK: 'Null Check requirement SKIPPED as schema validation is PASSED',
  ERROR_EXPECTED_NULL: 'Expected response.error to be null',
  ERROR_EXPECTED: 'Expected response.error not to be null',
  EXPECTED_ERROR_RESPONSE: 'Expected error in response:',
  PASS: 'PASS',
  SKIPPED: 'SKIPPED',
  FAIL: 'FAIL',
  SCHEMA_CHECK_SKIPPED: 'Assertion for Schema validation is skipped since skipSchemaValidation flag is true',
  EVENT: 'event',
  METHOD: 'method',
  FIRST_PARTY_APPID: 'firstPartyAppId',
  FIRST_PARTY_APP: '1st party app',
  EVENT_PARAM: 'event_param',
  VALIDATION_OBJECTS_PATH: 'cypress/fixtures/objects/validationObjects/',
  REGEX: 'regEx',
  MISC: 'misc',
  DECODE: 'decode',
  FIXTURE: 'fixture',
  ERROR_SCHEMA_OBJECTS_PATH: 'cypress/fixtures/objects/errorObjects/errorSchemaObject.json',
  ERROR_CONTENT_OBJECTS_PATH: 'cypress/fixtures/objects/errorObjects/errorContent.json',
  VALIDATION_FUNCTION: 'validationFunction',
  NOT_SUPPORTED: 'NOT_SUPPORTED',
  CONTENT: 'Content',
  ERROR: 'error',
  EVENT_ERROR_MSG: "Event listener error validation",
  EVENT_SCHEMA_MSG: "Event listener schema validation"
};
