name: Main Release to GitHub

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    uses: ./.github/workflows/release.yaml
    with:
      branch: 'main'
    secrets:
      SEMANTIC_RELEASE_BOT_PAT: ${{ secrets.SEMANTIC_RELEASE_BOT_PAT }}

  merge-main-to-dev:
    name: Merge main back to dev
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_BOT_PAT }}

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ secrets.GITHUB_EMAIL }}"

      - name: Fetch latest branches
        run: git fetch origin

      - name: Merge main into dev
        run: |
          git checkout dev
          git pull origin dev
          git merge origin/main --no-ff
          git push origin dev