name: Main Release to GitHub

on:
  workflow_dispatch:

jobs:
  check-team-membership:
    runs-on: ubuntu-latest
    steps:
      - name: Check team membership
        id: check_team
        run: |
          TEAM_NAME="${{ secrets.RELEASE_TEAM_NAME }}"
          ORG_NAME="rdkcentral"
          USERNAME="${{ github.actor }}"

          # Check if the user is part of the specified team
          IS_MEMBER=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/orgs/$ORG_NAME/teams/$TEAM_NAME/memberships/$USERNAME \
            | jq -r '.state')

          if [ "$IS_MEMBER" != "active" ]; then
            echo "User is not a member of the $TEAM_NAME team"
            exit 1
          fi

  validate-dev:
    needs: check-team-membership
    uses: ./.github/workflows/lint-and-sample-feature-run.yaml
    with:
      branch: 'dev'
